TYPO3:

  Flow:
    security:
      authentication:
        providers:
          'Typo3BackendProvider':
            requestPatterns:
              'Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern': 'backend'
          'Flowpack.Neos.FrontendLogin:Frontend':
            provider: 'PersistedUsernamePasswordProvider'
            requestPatterns:
              'Flowpack\Neos\FrontendLogin\Security\NeosRequestPattern': 'frontend'

  Neos:
    typoScript:
      autoInclude:
        'Flowpack.Neos.FrontendLogin': TRUE

    userInterface:
      translation:
        autoInclude:
          'Flowpack.Neos.FrontendLogin': ['NodeTypes/*']

Flowpack:
  Neos:
    FrontendLogin:
      translation:
        packageKey: 'Flowpack.Neos.FrontendLogin'
        sourceName: 'Main'